"""
NGNotes: Engineering Notes to Report Converter
Core conversion logic
"""

import os
import json
from typing import Optional, Dict, List
from dataclasses import dataclass

from models import ModelConfig, EvaluationResult, get_all_model_configs
from evaluation import evaluate_summary


@dataclass
class SummaryResult:
    """Result of a summary generation"""
    summary: str
    model_config: ModelConfig
    evaluation: EvaluationResult
    
    def to_dict(self) -> dict:
        """Convert result to dictionary"""
        return {
            'summary': self.summary,
            'model_config': str(self.model_config),
            'evaluation': self.evaluation.to_dict()
        }


class NGNotesConverter:
    """Main converter class for processing engineering notes"""
    
    def __init__(self):
        """Initialize the converter"""
        self.model_configs = get_all_model_configs()
    
    def load_engineering_notes(self, file_path: str) -> Optional[str]:
        """
        Load engineering notes from a file
        
        Args:
            file_path (str): Path to the input file
            
        Returns:
            Optional[str]: Content of the file or None if error
        """
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            print(f"Error reading file {file_path}: {e}")
            return None
    
    def get_model_config(self, model_name: str) -> Optional[ModelConfig]:
        """
        Get model configuration by name
        
        Args:
            model_name (str): Name of the model
            
        Returns:
            Optional[ModelConfig]: Model configuration or None if not found
        """
        for config in self.model_configs:
            if config.name == model_name:
                return config
        return None
    
    def generate_summary(self, notes: str, model_config: ModelConfig) -> SummaryResult:
        """
        Generate a summary using the specified model
        
        Args:
            notes (str): Engineering notes to summarize
            model_config (ModelConfig): Configuration for the model
            
        Returns:
            SummaryResult: Generated summary with evaluation
        """
        # This is a placeholder implementation
        # In a real implementation, this would call the actual LLM API
        
        print(f"Generating summary using {model_config.name}...")
        
        # Placeholder summary - in reality this would be generated by an LLM
        # For demonstration purposes, we'll create a more realistic summary
        if len(notes) > 200:
            summary = f"Summary generated with {model_config.name}: {notes[:200]}... (truncated)"
        else:
            summary = f"Summary generated with {model_config.name}: {notes}"
        
        # Evaluate the generated summary
        evaluation = evaluate_summary(notes, summary)
        
        return SummaryResult(
            summary=summary,
            model_config=model_config,
            evaluation=evaluation
        )
    
    def run_parameter_sweep(self, notes: str) -> Dict[str, SummaryResult]:
        """
        Run parameter sweep across all available models
        
        Args:
            notes (str): Engineering notes to summarize
            
        Returns:
            Dict[str, SummaryResult]: Dictionary mapping model names to results
        """
        print("Running parameter sweep...")
        results = {}
        
        for config in self.model_configs:
            result = self.generate_summary(notes, config)
            results[config.name] = result
        
        return results
    
    def compare_models(self, summaries: Dict[str, SummaryResult]) -> dict:
        """
        Compare models and determine the best result
        
        Args:
            summaries (Dict[str, SummaryResult]): Dictionary of model results
            
        Returns:
            dict: Comparison results including best model and overall best summary
        """
        print("Comparing models...")
        
        # For now, we'll use a simple comparison based on evaluation metrics
        # In reality, this would be more sophisticated
        
        best_model = None
        best_score = -1
        best_summary = ""
        
        for model_name, result in summaries.items():
            # Calculate a combined score (this is a simplified approach)
            score = (result.evaluation.rouge_l_f1 + result.evaluation.semantic_similarity) / 2
            
            if score > best_score:
                best_score = score
                best_model = model_name
                best_summary = result.summary
        
        return {
            'best_model': best_model,
            'overall_best_summary': best_summary,
            'all_results': summaries
        }
    
    def save_summary(self, summary: str, file_path: str) -> bool:
        """
        Save the generated summary to a file
        
        Args:
            summary (str): Summary text to save
            file_path (str): Path to output file
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(summary)
            return True
        except Exception as e:
            print(f"Error saving summary to {file_path}: {e}")
            return False
    
    def save_results(self, results: dict, file_path: str) -> bool:
        """
        Save comparison results to a JSON file
        
        Args:
            results (dict): Comparison results
            file_path (str): Path to output file
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(results, f, indent=2, default=str)
            return True
        except Exception as e:
            print(f"Error saving results to {file_path}: {e}")
            return False
    
    def save_summary(self, summary: str, file_path: str) -> bool:
        """
        Save the generated summary to a file
        
        Args:
            summary (str): Summary text to save
            file_path (str): Path to output file
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(summary)
            return True
        except Exception as e:
            print(f"Error saving summary to {file_path}: {e}")
            return False
    
    def save_results(self, results: dict, file_path: str) -> bool:
        """
        Save comparison results to a JSON file
        
        Args:
            results (dict): Comparison results
            file_path (str): Path to output file
            
        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(results, f, indent=2, default=str)
            return True
        except Exception as e:
            print(f"Error saving results to {file_path}: {e}")
            return False
